### ISSUE TITLE
The test suite does not work on Node 4.3

### ISSUE THREAD

**Issue by nickve28** [micro-toolkit/event-bus-zeromq#25]
A set of tests in the test suite fail when running on Node.js 4.3, with the following error:

32) Subscriber Module .close should persist last sequence number:
     TypeError: utf8 is not a function
      at Function.from (native)

The code in test/support/frames_helper.js calls Buffer.from, which is not a function in Node 4.3 and possibly other versions.

**Comment by pjanuario** [comment]
As we can see the tests pass on node.js > 4

https://travis-ci.org/micro-toolkit/event-bus-zeromq/builds/193420115

Most likely this was caused by some bug in that specific minor version that is now fixed.
